#!/bin/sh
BREW_PREFIX="$(brew --prefix 2>/dev/null || echo /opt/homebrew)"
case "${PINENTRY_USER_DATA-}" in
  *USE_TTY=1*)
    exec "${BREW_PREFIX}/bin/pinentry-tty" "$@"
    ;;
esac
exec "${BREW_PREFIX}/bin/pinentry-mac" "$@"
