#!/bin/sh

find_command() {
  command -v "$1" 2>/dev/null
}

try_exec() {
  candidate="$1"
  shift

  if [ -n "$candidate" ] && [ -x "$candidate" ]; then
    exec "$candidate" "$@"
  fi
}

BREW_PREFIX="$(brew --prefix 2>/dev/null || true)"
case "${PINENTRY_USER_DATA-}" in
  *USE_TTY=1*)
    try_exec "$(find_command pinentry-tty)" "$@"
    try_exec "$(find_command pinentry-curses)" "$@"
    try_exec "$(find_command pinentry)" "$@"
    ;;
esac

try_exec "${BREW_PREFIX:+${BREW_PREFIX}/bin/pinentry-mac}" "$@"
try_exec "$(find_command pinentry-mac)" "$@"
try_exec "$(find_command pinentry-curses)" "$@"
try_exec "$(find_command pinentry-tty)" "$@"
try_exec "$(find_command pinentry)" "$@"

echo "No pinentry program found" >&2
exit 127
